---
- name: 'copy dockerhub password'
  copy:
    dest: "/home/{{ build_user }}/docker_password.txt"
    content: "{{ secret_dockerhub_user_password }}"
    mode: 0644
    owner: "{{ build_user }}"
    group: "{{ build_user }}"

- name: 'login to dockerhub for pushing images'
  shell: |
    cat docker_password.txt | docker login --username {{ dockerhub_user }} --password-stdin
  args:
    chdir: "/home/{{ build_user }}"
  become: yes
  become_user: "{{ build_user }}"
  ignore_errors: yes

- name: 'copy login script'
  template:
    src: docker_login.sh
    dest: "/home/{{ build_user }}/docker_password.txt"
    content: "{{ secret_dockerhub_user_password }}"
    mode: 0755
    owner: "{{ build_user }}"
    group: "{{ build_user }}"

- name: 'pull docker images for slave'
  docker_image:
    name: "{{ item }}"
  with_items:
    - "{{ safe_client_libs_build_image_name }}:{{ safe_client_libs_build_image_tag }}"
    - "{{ safe_nd_build_image_name }}:{{ safe_nd_build_image_tag }}"
    - "{{ safe_cli_build_image_name }}:{{ safe_cli_build_image_tag }}"
