plugins:
  sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
{% if cloud_environment == "prod" or cloud_environment == "staging" or cloud_environment == "qa" %}
    globalMatrix:
      grantedPermissions:
      - "Overall/Read:anonymous"
      - "Overall/Read:authenticated"
      - "Overall/Read:Administrators"
      - "Overall/Read:maidsafe*QA"
      - "Overall/Administer:maidsafe*QA"
      - "Overall/Administer:Administrators"
      - "Overall/Administer:{{ jenkins_admin_user }}"
      - "Job/Workspace:maidsafe*developers"
      - "Job/Cancel:maidsafe*developers"
      - "Job/Read:anonymous"
      - "Job/Read:maidsafe*developers"
      - "Job/Build:maidsafe*developers"
      - "Job/Discover:maidsafe*developers"
      - "Run/Update:maidsafe*developers"
      - "Run/Replay:maidsafe*developers"
      - "View/Delete:maidsafe*developers"
      - "View/Configure:maidsafe*developers"
      - "View/Read:maidsafe*developers"
      - "View/Create:maidsafe*developers"
{% else %}
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:authenticated"
        - "Overall/Read:Administrators"
        - "Overall/Administer:{{ jenkins_admin_user }}"
        - "Overall/Administer:Administrators"
{% endif %}
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
{% if cloud_environment == "prod" or cloud_environment == "staging" or cloud_environment == "qa" %}
  clouds:
    - amazonEC2:
        cloudName: "jenkins"
        credentialsId: "jenkins-ec2"
        instanceCapStr: ""
        privateKey: ""
        region: "eu-west-2"
        templates:
          - ami: "{{ docker_slave_ami_id }}"
            amiType:
              unixData:
                sshPort: "22"
            associatePublicIp: false
            connectBySSHProcess: false
            connectUsingPublicIp: false
            deleteRootOnTermination: false
            description: "{{ docker_slave_full_name }}"
            ebsOptimized: false
            idleTerminationMinutes: "30"
            labelString: "docker"
            mode: NORMAL
            monitoring: false
            numExecutors: 1
            remoteAdmin: "jenkins"
            remoteFS: "{{ jenkins_workspace_mount_point }}"
            securityGroups: "{{ linux_slaves_security_group_name }}"
            stopOnTerminate: false
            subnetId: "{{ slave_vpc_subnet_id }}"
            t2Unlimited: false
            type: T2Medium
            useDedicatedTenancy: false
            useEphemeralDevices: false
            usePrivateDnsName: false
        useInstanceProfileForCredentials: false
{% endif %}
  nodes:
{% if cloud_environment == "dev" %}
{% for slave in groups['linux_slaves'] %}
    - permanent:
        launcher:
          sSHLauncher:
            credentialsId: "docker_slave_jenkins_user_ssh_key"
            host: "{{ hostvars[slave]['ec2_private_ip_address'] }}"
            launchTimeoutSeconds: 210
            maxNumRetries: 10
            port: 22
            retryWaitTime: 15
        name: "{{ hostvars[slave]['ec2_tag_full_name'] }}"
        labelString: "docker"
        numExecutors: 1
        remoteFS: "/home/jenkins"
{% endfor %}
{% endif %}
{% if cloud_environment != "none" %}
{% for slave in groups['windows_slaves'] %}
    - permanent:
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
        name: "{{ hostvars[slave]['ec2_tag_full_name'] }}"
        labelString: "windows"
        numExecutors: 1
        # This variable must be without quotes for the Windows style path
        remoteFS: {{ windows_rust_slave_working_path }}
{% endfor %}
{% if cloud_environment == "prod" or cloud_environment == "staging" or cloud_environment == "qa" %}
    - permanent:
        launcher:
          sSHLauncher:
            credentialsId: "docker_slave_jenkins_user_ssh_key"
            host: "{{ osx_rust_slave_ip_address }}"
            launchTimeoutSeconds: 210
            maxNumRetries: 10
            port: 22
            retryWaitTime: 15
        name: "{{ osx_rust_slave_full_name }}"
        labelString: "osx"
        numExecutors: 1
        remoteFS: "{{ macos_jenkins_workspace }}"
{% endif %}
{% else %}
    - permanent:
        launcher:
          sSHLauncher:
            credentialsId: "docker_slave_jenkins_user_ssh_key"
            host: "{{ docker_slave_ip_address }}"
            launchTimeoutSeconds: 210
            maxNumRetries: 10
            port: 22
            retryWaitTime: 15
        name: "{{ docker_slave_full_name }}"
        labelString: "docker"
        numExecutors: 1
        remoteFS: "/home/jenkins"
    - permanent:
        launcher:
          jnlp:
            workDirSettings:
              disabled: false
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
        name: "{{ windows_rust_slave_full_name }}"
        labelString: "windows"
        numExecutors: 1
        # This variable must be without quotes for the Windows style path
        remoteFS: {{ windows_rust_slave_working_path }}
    - permanent:
        launcher:
          sSHLauncher:
            credentialsId: "docker_slave_jenkins_user_ssh_key"
            host: "{{ osx_rust_slave_ip_address }}"
            launchTimeoutSeconds: 210
            maxNumRetries: 10
            port: 22
            retryWaitTime: 15
        name: "{{ osx_rust_slave_full_name }}"
        labelString: "osx"
        numExecutors: 2
        remoteFS: "{{ macos_jenkins_workspace }}"
{% endif %}
  numExecutors: 1
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "{{ jenkins_admin_user }}"
          password: ${secret_jenkins_admin_user_password}
  slaveAgentPort: 50000
  views:
    - all:
        name: "all"
  remotingSecurity:
    enabled: true
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
security:
  remotingCLI:
    enabled: false
credentials:
  system:
    domainCredentials:
      - credentials:
        - basicSSHUserPrivateKey:
            id: "docker_slave_jenkins_user_ssh_key"
            privateKeySource:
              directEntry:
                privateKey: ${secret_docker_slave_ssh_key}
            scope: GLOBAL
            username: "jenkins"
        - usernamePassword:
            id: "aws_jenkins_user_credentials"
            password: ${secret_aws_jenkins_secret_key}
            scope: GLOBAL
            username: "{{ aws_jenkins_access_key }}"
        - usernamePassword:
            id: "aws_jenkins_build_artifacts_user"
            password: ${secret_aws_jenkins_build_user_secret_key}
            scope: GLOBAL
            username: "AKIAVVODCRMSJRUPZZHN"
        - usernamePassword:
            id: "github_maidsafe_token_credentials"
            password: ${secret_github_access_token}
            scope: GLOBAL
            username: "maidsafe"
        - usernamePassword:
            id: "github_maidsafe_qa_user_credentials"
            password: ${secret_github_maidsafe_qa_user_password}
            scope: GLOBAL
            username: "maidsafe"
        - aws:
            accessKey: "AKIAVVODCRMSJYOPDR5R"
            description: "User for controlling the EC2 plugin."
            id: "jenkins-ec2"
            scope: GLOBAL
            secretKey: "{{ secret_aws_jenkins_ec2_user_secret_access_key }}"
        - string:
            id: "github_maidsafe_token_secret_text"
            scope: GLOBAL
            secret: ${secret_github_access_token}
unclassified:
  githubpluginconfig:
    configs:
    - apiUrl: "https://api.github.com"
      credentialsId: "github_maidsafe_token_secret_text"
      name: "maidsafe"
  location:
    url: "{{ jenkins_master_url  }}"
    adminAddress: "qa@maidsafe.net"
