---
docker_slave_ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSPzCgOC8ykMhEHPy3V59eQkgPG2QSJBEX7O22mHFLwXueVD3EF2cXLl9m9TEXKyS38HvFGDIXDJljLYIT0Cm3g23XMQmWRkaqBqOI/LZpuDYcRTxq3Ev6C30MQKo1qQuXLUdiTFP+izAXE5e19Sslw/++3JboFwYZbDhyphVxxmz7u83KKh5qpEm1ZUSGLmm00TMdgy+M6BpUtehV3UDnM/eeTbLXwI12M+EcFrbZU/+lSmy+B8jdT0WiEc84slYx0y9bUtx4IcGKG5tgrhlJwzdb49OEcSaXMxajTKREPxoIqk9Af79yxbJWUGSZyYS/YY10/CzDgo2n4jeZaaVP
docker_storage_block_device: /dev/xvdc
docker_storage_mount_point: /var/lib/docker
jenkins_workspace_block_device: /dev/xvdb
jenkins_workspace_mount_point: /mnt/jenkins_workspace
