---
- name: 'create .ansible directory'
  file:
    path: "/home/{{ provisioning_user }}/.ansible"
    state: directory
    mode: 0700
    owner: "{{ provisioning_user }}"
    group: "{{ provisioning_user }}"

- name: 'set the ansible vault password'
  copy:
    content: "{{ ansible_vault_password }}"
    dest: "/home/{{ provisioning_user }}/.ansible/vault-pass"
    mode: 0600
    owner: "{{ provisioning_user }}"
    group: "{{ provisioning_user }}"

- name: 'install utils'
  package:
    name: ['git', 'vim']

- name: 'install netcat (centos)'
  package:
    name: 'nc'
  when: ansible_distribution == 'CentOS'

- name: 'install netcat (ubuntu)'
  package:
    name: 'netcat'
  when: ansible_distribution == 'Ubuntu'

- name: 'install jq'
  get_url:
    url: "{{ jq_url }}"
    dest: "{{ jq_install_path }}"
    mode: 0755

- name: 'install python (Ubuntu)'
  package:
    name: python
  when: ansible_distribution == 'Ubuntu'

- name: 'install system virtualenv'
  pip:
    name: virtualenv

- name: 'create /etc/ansible directory'
  file:
    path: "/etc/ansible"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: 'copy ec2.ini for dynamic inventory'
  template:
    src: ec2.ini
    dest: /etc/ansible/ec2.ini
    owner: root
    group: root

- name: 'create virtualenv location'
  file:
    path: "{{ virtualenv_path }}"
    state: directory
    mode: 0700
    owner: "{{ provisioning_user }}"
    group: "{{ provisioning_user }}"

- name: 'create provisioning virtualenv'
  command: "virtualenv {{ virtualenv_name }}"
  args:
    chdir: "{{ virtualenv_path }}"
  become: yes
  become_user: "{{ provisioning_user }}"

# You are supposed to be able to use the 'virtualenv' parameter of the pip module to
# install packages into a virtualenv, but it wasn't working correctly.
- name: 'install ansible dependencies'
  shell: |
    . {{ provisioning_virtualenv_path }}/bin/activate
    pip install {{ item }}
  with_items:
    - awscli
    - "ansible=={{ ansible_provisioner_version }}"
    - boto
    - boto3
    - pypsrp
  become: yes
  become_user: "{{ provisioning_user }}"
