---
- name: 'setup the haproxy repository'
  apt_repository:
    repo: "{{ haproxy_repository }}"
    state: present

- name: 'install haproxy'
  package:
    name: haproxy

- name: 'copy haproxy config'
  template:
    src: haproxy.cfg
    dest: "{{ haproxy_config_path }}"
    owner: root
    group: root
    mode: 0644
  when: run_mode == 'initial'

- name: 'copy renew script'
  template:
    src: update_certificates
    dest: "{{ update_certificates_script_path }}"
    owner: root
    group: root
    mode: 0744

- name: 'cron job for renewing certificates'
  cron:
    name: update_certificates
    hour: 2
    minute: 0
    job: "{{ update_certificates_script_path }}"

- name: 'start haproxy'
  service:
    name: haproxy
    state: restarted
    enabled: yes
